import { Event } from "@/hooks/useEvents";

export const FAKE_EVENTS: Event[] = [
  {
    id: "fake-event-1",
    user_id: "fake-user",
    project_id: "fake-proj-1",
    title: "Réunion équipe chantier",
    description: "Point hebdomadaire sur l'avancement des travaux - Maison Martin",
    start_date: new Date().toISOString(),
    end_date: new Date(Date.now() + 3600000).toISOString(),
    all_day: false,
    location: "Bureau principal",
    type: "meeting",
    color: "#3b82f6",
    reminder_minutes: 15,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    project_name: "Rénovation Maison Martin",
  },
  {
    id: "fake-event-2",
    user_id: "fake-user",
    project_id: "fake-proj-2",
    title: "Livraison matériaux",
    description: "Réception des matériaux pour le chantier Dupont",
    start_date: new Date(Date.now() + 86400000).toISOString(),
    all_day: true,
    type: "task",
    color: "#10b981",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    project_name: "Extension Garage Dupont",
  },
  {
    id: "fake-event-3",
    user_id: "fake-user",
    title: "Échéance devis Dubois",
    description: "Rappel : devis à envoyer avant le 15 janvier",
    start_date: new Date(Date.now() + 172800000).toISOString(),
    all_day: false,
    type: "deadline",
    color: "#f59e0b",
    reminder_minutes: 60,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fake-event-4",
    user_id: "fake-user",
    title: "Visite chantier",
    description: "Visite de contrôle qualité sur le chantier Martin",
    start_date: new Date(Date.now() + 259200000).toISOString(),
    end_date: new Date(Date.now() + 259200000 + 7200000).toISOString(),
    all_day: false,
    location: "12 Rue de la République, 75001 Paris",
    type: "meeting",
    color: "#8b5cf6",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    project_name: "Rénovation Maison Martin",
  },
];


