import type { Invoice } from "@/hooks/useInvoices";

export const FAKE_INVOICES: Invoice[] = [
  {
    id: "fake-invoice-1",
    user_id: "fake-user",
    invoice_number: "FACTURE-2025-001",
    client_id: "fake-client-1",
    client_name: "M. Martin",
    client_email: "martin@example.com",
    client_address: "Paris, 75001",
    description: "Rénovation toiture complète",
    amount_ht: 37500,
    vat_rate: 20,
    vat_amount: 7500,
    amount_ttc: 45000,
    status: "paid",
    payment_status: "paid",
    due_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    paid_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    service_lines: [
      { description: "Démolition ancienne toiture", quantity: 1, unit_price: 5000, total: 5000 },
      { description: "Pose nouvelle charpente", quantity: 1, unit_price: 15000, total: 15000 },
      { description: "Pose tuiles", quantity: 120, unit_price: 50, total: 6000 },
      { description: "Isolation", quantity: 100, unit_price: 80, total: 8000 },
      { description: "Zinguerie", quantity: 1, unit_price: 3500, total: 3500 },
    ],
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fake-invoice-2",
    user_id: "fake-user",
    invoice_number: "FACTURE-2025-002",
    client_id: "fake-client-2",
    client_name: "Mme. Dupont",
    client_email: "dupont@example.com",
    client_address: "Lyon, 69001",
    description: "Extension garage",
    amount_ht: 15000,
    vat_rate: 20,
    vat_amount: 3000,
    amount_ttc: 18000,
    status: "signed",
    payment_status: "pending",
    due_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    signed_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    signed_by: "Mme. Dupont",
    service_lines: [
      { description: "Maçonnerie", quantity: 1, unit_price: 8000, total: 8000 },
      { description: "Charpente", quantity: 1, unit_price: 4000, total: 4000 },
      { description: "Couverture", quantity: 1, unit_price: 3000, total: 3000 },
    ],
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fake-invoice-3",
    user_id: "fake-user",
    invoice_number: "FACTURE-2025-003",
    client_id: "fake-client-3",
    client_name: "Entreprise Bernard",
    client_email: "contact@bernard.fr",
    client_address: "Marseille, 13001",
    description: "Rénovation électrique",
    amount_ht: 7083.33,
    vat_rate: 20,
    vat_amount: 1416.67,
    amount_ttc: 8500,
    status: "draft",
    payment_status: "pending",
    service_lines: [
      { description: "Mise aux normes électrique", quantity: 1, unit_price: 5000, total: 5000 },
      { description: "Tableau électrique", quantity: 1, unit_price: 1500, total: 1500 },
      { description: "Prises et interrupteurs", quantity: 20, unit_price: 25, total: 500 },
      { description: "Main d'œuvre", quantity: 1, unit_price: 500, total: 500 },
    ],
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];



