import { Payment } from "@/hooks/usePayments";

export const FAKE_PAYMENTS: Payment[] = [
  {
    id: "fake-payment-1",
    user_id: "fake-user",
    project_id: null,
    quote_id: null,
    invoice_id: null,
    client_id: null,
    amount: 54000,
    due_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    paid_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "paid",
    payment_method: "Virement bancaire",
    reference: "PAY-2025-001",
    notes: "Paiement pour rénovation toiture - M. Martin",
    reminder_sent_at: null,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fake-payment-2",
    user_id: "fake-user",
    project_id: null,
    quote_id: null,
    invoice_id: null,
    client_id: null,
    amount: 21600,
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    paid_date: null,
    status: "pending",
    payment_method: "Chèque",
    reference: "PAY-2025-002",
    notes: "Extension garage - Mme. Dupont",
    reminder_sent_at: null,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fake-payment-3",
    user_id: "fake-user",
    project_id: null,
    quote_id: null,
    invoice_id: null,
    client_id: null,
    amount: 10200,
    due_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    paid_date: null,
    status: "overdue",
    payment_method: "Virement bancaire",
    reference: "PAY-2025-003",
    notes: "Rénovation électrique - Paiement en retard",
    reminder_sent_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

