import { Payment } from "@/hooks/usePayments";

export const FAKE_PAYMENTS: Payment[] = [
  {
    id: "fake-payment-1",
    user_id: "fake-user",
    project_id: "fake-proj-1",
    quote_id: "fake-quote-1",
    invoice_id: "fake-invoice-1",
    client_id: "fake-client-1",
    amount: 45000,
    due_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    paid_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "paid",
    payment_method: "Virement bancaire",
    reference: "PAY-2025-001",
    notes: "Paiement pour rénovation toiture - M. Martin",
    reminder_sent_at: null,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fake-payment-2",
    user_id: "fake-user",
    project_id: "fake-proj-2",
    quote_id: "fake-quote-2",
    invoice_id: "fake-invoice-2",
    client_id: "fake-client-2",
    amount: 18000,
    due_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    paid_date: null,
    status: "pending",
    payment_method: "Chèque",
    reference: "PAY-2025-002",
    notes: "Extension garage - Mme. Dupont",
    reminder_sent_at: null,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fake-payment-3",
    user_id: "fake-user",
    project_id: "fake-proj-3",
    quote_id: "fake-quote-3",
    invoice_id: "fake-invoice-3",
    client_id: "fake-client-3",
    amount: 8500,
    due_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    paid_date: null,
    status: "overdue",
    payment_method: "Virement bancaire",
    reference: "PAY-2025-003",
    notes: "Rénovation électrique - Paiement en retard",
    reminder_sent_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fake-payment-4",
    user_id: "fake-user",
    project_id: "fake-proj-4",
    quote_id: "fake-quote-4",
    invoice_id: "fake-invoice-4",
    client_id: "fake-client-4",
    amount: 32500,
    due_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    paid_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "paid",
    payment_method: "Carte bancaire",
    reference: "PAY-2025-004",
    notes: "Acompte 50% - Construction terrasse et véranda",
    reminder_sent_at: null,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fake-payment-5",
    user_id: "fake-user",
    project_id: "fake-proj-5",
    quote_id: null,
    invoice_id: "fake-invoice-5",
    client_id: "fake-client-5",
    amount: 25000,
    due_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    paid_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "paid",
    payment_method: "Virement bancaire",
    reference: "PAY-2025-005",
    notes: "Rénovation salle de bain - SARL Construction Moderne",
    reminder_sent_at: null,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "fake-payment-6",
    user_id: "fake-user",
    project_id: "fake-proj-1",
    quote_id: null,
    invoice_id: null,
    client_id: "fake-client-1",
    amount: 32500,
    due_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    paid_date: null,
    status: "pending",
    payment_method: "Virement bancaire",
    reference: "PAY-2025-006",
    notes: "Solde - Construction terrasse et véranda",
    reminder_sent_at: null,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

