import { Project } from "@/hooks/useProjects";

export const FAKE_PROJECTS: Project[] = [
  {
    id: "fake-proj-1",
    user_id: "fake-user",
    client_id: "fake-client-1",
    name: "Rénovation Maison Martin",
    description: "Rénovation complète d'une maison de 120m² : maçonnerie, plomberie, électricité, peinture",
    status: "en_cours",
    budget: 45000,
    costs: 32000,
    benefice: 13000,
    location: "12 Rue de la République, 75001 Paris",
    start_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    end_date: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    created_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    client: {
      id: "fake-client-1",
      name: "M. Martin",
      email: "martin@example.fr",
    },
  },
  {
    id: "fake-proj-2",
    user_id: "fake-user",
    client_id: "fake-client-2",
    name: "Extension Garage Dupont",
    status: "planifié",
    budget: 18000,
    costs: 0,
    benefice: 0,
    location: "45 Avenue des Champs, 69000 Lyon",
    start_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    end_date: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    client: {
      id: "fake-client-2",
      name: "Mme. Dupont",
      email: "dupont@example.fr",
    },
  },
  {
    id: "fake-proj-3",
    user_id: "fake-user",
    client_id: "fake-client-3",
    name: "Peinture Bureau Bernard",
    status: "terminé",
    budget: 8500,
    costs: 6200,
    benefice: 2300,
    location: "78 Rue du Commerce, 13000 Marseille",
    start_date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    end_date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    created_at: new Date(Date.now() - 95 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    client: {
      id: "fake-client-3",
      name: "Entreprise Bernard",
      email: "bernard@example.fr",
    },
  },
  {
    id: "fake-proj-4",
    user_id: "fake-user",
    client_id: "fake-client-1",
    name: "Réfection Toiture",
    status: "en_attente",
    budget: 25000,
    costs: 0,
    benefice: 0,
    location: "12 Rue de la République, 75001 Paris",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    client: {
      id: "fake-client-1",
      name: "M. Martin",
      email: "martin@example.fr",
    },
  },
];


